### ISSUE TITLE
Make sure the module still works with master

### ISSUE THREAD

**Issue by fire** [godotengine/godot-visual-script#1]
Master moves fast.

**Comment by akien-mga** [comment]
Well as of right now it still works with master.
What is the actionable item for this issue?

**Comment by fire** [comment]
Make a github action that periodically checks master builds.

I can design it.

**Comment by fire** [comment]
```
name: Check godot master
on:
  schedule:
    - cron: "20 1 * * *"
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
```
```
```
